[package]
name          = "str"
version       = "0.1.0"
license       = "MIT"
authors       = ["dangcheng <dangcheng@hotmail.com>"]
description   = "string extension"
homepage      = "https://github.com/mcorce/str"
repository    = "https://github.com/mcorce/str"
readme        = "README.md"
keywords      = ["str", "string"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
